pyhon_tesseract/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tesseract.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

tesseract/urls.py
from .import views
from django.conf.urls import url

urlpatterns = [
    url(r'^', views.TessView.as_view(), name='tess'),
]

tesseract/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Tess(models.Model):
    tess_name = models.CharField(max_length=200)
    tess_file = models.FileField()

    def __str__(self):
        return self.tess_name

templates/tess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tesseract</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <form method="post" enctype="multipart/form-data" id="upload_form">
        <input type="hidden" name="ajax_key" class="ajax_key" value="upload_key"/>
        <!--<input type="hidden" name="save_id" class="save_id" value=""/>-->
        {% csrf_token %}
        <div class="form-group">
            <label>Name</label>
            <!--{{form.tess_name}}-->
            <input type="text" name="tess_name" required="" id="id_tess_name" maxlength="200" class="form-control">
        </div>

        <div class="form-group">
            <label>Choose File</label>
            <!--{{form.tess_file}}-->
            <input type="file" name="tess_file" required="" id="id_tess_file" class="form-control">
        </div>

        <input type="button" class="btn btn-success upload_btn" value="upload">
    </form>

    <div class="content " style="margin-top: 30px;"></div>
</div>

</body>
</html>
<script>
$(document).on('click', '.upload_btn', function(){
    var formData = new FormData();
    var img = $("#id_tess_file")[0].files[0];
    var other_data = $('#upload_form').serializeArray();
    $.each(other_data,function(key,input){
        formData.append(input.name,input.value);
    });
    formData.append("tess_file", img);
    console.log(formData);
    var url = window.location.href;
	$.ajax({
		type: "POST",
		data : formData,
        async: false,
        processData: false,
        contentType: false,
		success: function(data) {
		    if (data.status == true){
		        $('.content').html(data.html_content);
		    }else{
		        alert("name already exists...")
		        $('.error').remove();
                var $inputs = $('#upload_form :input');
                $.each(data.errors, function( name, value ) {
                    $inputs.each(function(index, dom){
                        current_name = dom.name;
                        if (current_name == name){
                            var $error_section = $(this).closest("div");
                            $error_section.append("<p class='error'>"+value+"</p>");
                        }
                    });
                });
		    }
		}
	});
});

</script>

templates/tesss.html
czdfvdfvdv